src/Entity/Budget.php
<?php

namespace App\Entity;

use App\Repository\BudgetRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BudgetRepository::class)]
class Budget
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'float')]
    private $InitialValue;

    #[ORM\Column(type: 'float')]
    private $ConsumedValue;

    #[ORM\Column(type: 'float')]
    private $RemainingBudget;

    #[ORM\Column(type: 'float')]
    private $TurnoverBudget;

    #[ORM\OneToMany(mappedBy: 'Budget', targetEntity: Projet::class)]
    private $projets;

    public function __construct()
    {
        $this->projets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getInitialValue(): ?float
    {
        return $this->InitialValue;
    }

    public function setInitialValue(float $InitialValue): self
    {
        $this->InitialValue = $InitialValue;

        return $this;
    }

    public function getConsumedValue(): ?float
    {
        return $this->ConsumedValue;
    }

    public function setConsumedValue(float $ConsumedValue): self
    {
        $this->ConsumedValue = $ConsumedValue;

        return $this;
    }

    public function getRemainingBudget(): ?float
    {
        return $this->RemainingBudget;
    }

    public function setRemainingBudget(float $RemainingBudget): self
    {
        $this->RemainingBudget = $RemainingBudget;

        return $this;
    }

    public function getTurnoverBudget(): ?float
    {
        return $this->TurnoverBudget;
    }

    public function setTurnoverBudget(float $TurnoverBudget): self
    {
        $this->TurnoverBudget = $TurnoverBudget;

        return $this;
    }

    /**
     * @return Collection|Projet[]
     */
    public function getProjets(): Collection
    {
        return $this->projets;
    }

    public function addProjet(Projet $projet): self
    {
        if (!$this->projets->contains($projet)) {
            $this->projets[] = $projet;
            $projet->setBudget($this);
        }

        return $this;
    }

    public function removeProjet(Projet $projet): self
    {
        if ($this->projets->removeElement($projet)) {
            // set the owning side to null (unless already changed)
            if ($projet->getBudget() === $this) {
                $projet->setBudget(null);
            }
        }

        return $this;
    }
}

src/Entity/Fact.php
<?php

namespace App\Entity;

use App\Repository\FactRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FactRepository::class)]
class Fact
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'datetime')]
    private $DateFact;

    #[ORM\Column(type: 'string', length: 255)]
    private $description;

    #[ORM\ManyToOne(targetEntity: Milestone::class, inversedBy: 'facts')]
    #[ORM\JoinColumn(nullable: false)]
    private $Milestone;

    #[ORM\ManyToOne(targetEntity: Projet::class, inversedBy: 'Fact')]
    private $projet;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDateFact(): ?\DateTimeInterface
    {
        return $this->DateFact;
    }

    public function setDateFact(\DateTimeInterface $DateFact): self
    {
        $this->DateFact = $DateFact;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getMilestone(): ?Milestone
    {
        return $this->Milestone;
    }

    public function setMilestone(?Milestone $Milestone): self
    {
        $this->Milestone = $Milestone;

        return $this;
    }

    public function getProjet(): ?Projet
    {
        return $this->projet;
    }

    public function setProjet(?Projet $projet): self
    {
        $this->projet = $projet;

        return $this;
    }
}

src/Entity/Projet.php
<?php

namespace App\Entity;

use App\Repository\ProjetRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JetBrains\PhpStorm\Pure;

#[ORM\Entity(repositoryClass: ProjetRepository::class)]
class Projet
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $Title;

    #[ORM\Column(type: 'text', nullable: true)]
    private $description;

    #[ORM\Column(type: 'date', nullable: true)]
    private $startDate;

    #[ORM\Column(type: 'date', nullable: true)]
    private $endedAt;

    #[ORM\ManyToOne(targetEntity: Status::class, inversedBy: 'projet')]
    private $status;

    #[ORM\ManyToOne(targetEntity: Portfolio::class, inversedBy: 'Projet')]
    private $portfolio;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $code;

    #[ORM\ManyToOne(targetEntity: Budget::class, inversedBy: 'projets')]
    private $Budget;

    #[ORM\OneToMany(mappedBy: 'projet', targetEntity: Risk::class)]
    private $Risk;

    #[ORM\Column(type: 'boolean')]
    private $Done;

    #[ORM\ManyToOne(targetEntity: Team::class, inversedBy: 'Projet')]
    #[ORM\JoinColumn(nullable: false)]
    private $team;

    #[ORM\OneToMany(mappedBy: 'projet', targetEntity: Fact::class)]
    private $Fact;

    #[ORM\OneToMany(mappedBy: 'projet', targetEntity: Milestone::class)]
    private $Milestone;

    public function __construct()
    {
        $this->Risk = new ArrayCollection();
        $this->Fact = new ArrayCollection();
        $this->Milestone = new ArrayCollection();
    }

    #[Pure] public function __toString(): string
    {
        return (string) $this->getTitle();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(?\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndedAt(): ?\DateTimeInterface
    {
        return $this->endedAt;
    }

    public function setEndedAt(?\DateTimeInterface $endedAt): self
    {
        $this->endedAt = $endedAt;

        return $this;
    }

    public function getStatus(): ?Status
    {
        return $this->status;
    }

    public function setStatus(?Status $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getPortfolio(): ?Portfolio
    {
        return $this->portfolio;
    }

    public function setPortfolio(?Portfolio $portfolio): self
    {
        $this->portfolio = $portfolio;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(?string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getBudget(): ?Budget
    {
        return $this->Budget;
    }

    public function setBudget(?Budget $Budget): self
    {
        $this->Budget = $Budget;

        return $this;
    }

    /**
     * @return Collection|Risk[]
     */
    public function getRisk(): Collection
    {
        return $this->Risk;
    }

    public function addRisk(Risk $risk): self
    {
        if (!$this->Risk->contains($risk)) {
            $this->Risk[] = $risk;
            $risk->setProjet($this);
        }

        return $this;
    }

    public function removeRisk(Risk $risk): self
    {
        if ($this->Risk->removeElement($risk)) {
            // set the owning side to null (unless already changed)
            if ($risk->getProjet() === $this) {
                $risk->setProjet(null);
            }
        }

        return $this;
    }

    public function getDone(): ?bool
    {
        return $this->Done;
    }

    public function setDone(bool $Done): self
    {
        $this->Done = $Done;

        return $this;
    }

    public function getTeam(): ?Team
    {
        return $this->team;
    }

    public function setTeam(?Team $team): self
    {
        $this->team = $team;

        return $this;
    }

    /**
     * @return Collection<int, Fact>
     */
    public function getFact(): Collection
    {
        return $this->Fact;
    }

    public function addFact(Fact $fact): self
    {
        if (!$this->Fact->contains($fact)) {
            $this->Fact[] = $fact;
            $fact->setProjet($this);
        }

        return $this;
    }

    public function removeFact(Fact $fact): self
    {
        if ($this->Fact->removeElement($fact)) {
            // set the owning side to null (unless already changed)
            if ($fact->getProjet() === $this) {
                $fact->setProjet(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Milestone>
     */
    public function getMilestone(): Collection
    {
        return $this->Milestone;
    }

    public function addMilestone(Milestone $milestone): self
    {
        if (!$this->Milestone->contains($milestone)) {
            $this->Milestone[] = $milestone;
            $milestone->setProjet($this);
        }

        return $this;
    }

    public function removeMilestone(Milestone $milestone): self
    {
        if ($this->Milestone->removeElement($milestone)) {
            // set the owning side to null (unless already changed)
            if ($milestone->getProjet() === $this) {
                $milestone->setProjet(null);
            }
        }

        return $this;
    }
}

src/Entity/Tag.php
<?php

namespace App\Entity;

use App\Repository\MilestoneRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MilestoneRepository::class)]
class Milestone
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'integer')]
    private $value;

    #[ORM\Column(type: 'boolean')]
    private $Mandatory;

    #[ORM\OneToMany(mappedBy: 'Milestone', targetEntity: CrucialFact::class)]
    private $crucialFacts;

    public function __construct()
    {
        $this->crucialFacts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getValue(): ?int
    {
        return $this->value;
    }

    public function setValue(int $value): self
    {
        $this->value = $value;

        return $this;
    }

    public function getMandatory(): ?bool
    {
        return $this->Mandatory;
    }

    public function setMandatory(bool $Mandatory): self
    {
        $this->Mandatory = $Mandatory;

        return $this;
    }

    /**
     * @return Collection|CrucialFact[]
     */
    public function getCrucialFacts(): Collection
    {
        return $this->crucialFacts;
    }

    public function addCrucialFact(CrucialFact $crucialFact): self
    {
        if (!$this->crucialFacts->contains($crucialFact)) {
            $this->crucialFacts[] = $crucialFact;
            $crucialFact->setMilestone($this);
        }

        return $this;
    }

    public function removeCrucialFact(CrucialFact $crucialFact): self
    {
        if ($this->crucialFacts->removeElement($crucialFact)) {
            // set the owning side to null (unless already changed)
            if ($crucialFact->getMilestone() === $this) {
                $crucialFact->setMilestone(null);
            }
        }

        return $this;
    }
}

templates/project/_form.html.twig
{{ form_start(form) }}
<div class="d-md-flex">
    <div class="col-12 col-md-6">
        {{ form_label(form.code, "Code") }}
        {{ form_widget(form.code) }}

        {{ form_label(form.Title, "Title") }}
        {{ form_widget(form.Title) }}
        <div class="col-12 col-md-6">
        {{ form_label(form.description, "Description") }}
        {{ form_widget(form.description) }}
        </div>

        {{ form_label(form.status, "Statut") }}
        {{ form_widget(form.status) }}

        <div class="mb-3">
            {{ form_label(form.startDate, "Début") }}
            {{ form_widget(form.startDate.date) }}
            <div class="d-none">
                {{ form_widget(form.startDate.time.hour) }}
                {{ form_widget(form.startDate.time.minute) }}
            </div>
        </div>
    </div>

    <div class="col-12 col-md-6 p-3">
        {{ form_label(form.portfolio, "Portfolio") }}
        {{ form_widget(form.portfolio) }}

        {{ form_label(form.team, "Équipe") }}
        {{ form_widget(form.team, {
            attr: {
                class: "mb-3"
            }
        }) }}

        <div class="mb-3">
            <div class="text-center">
                {{ form_label(form.budget, "Budget") }}
            </div>

            {{ form_label(form.budget.InitialValue, "Initial") }}
            {{ form_widget(form.budget.InitialValue, {
                attr: {
                    class: "mb-3"
                }
            }) }}

            {{ form_label(form.budget.ConsumedValue, "Consommé") }}
            {{ form_widget(form.budget.ConsumedValue, {
                attr: {
                    class: "mb-3"
                }
            }) }}
        </div>
    </div>
</div>

<div class="text-center mb-3">
    <button class="btn btn-dark">
        {{ button_label|default('Enregistrer') }}
    </button>
</div>

{{ form_end(form) }}

templates/project/dashboard.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tableau de bord{% endblock %}

{% block body %}

    {% include 'base/nav.html.twig' %}

    {% if app.user %}

        <div class="container-fluid">
            <h1>Tableau de bord</h1>
            <div class="row">
                <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6">
                    <div class="container">
                        <div class="row">
                            <div class="col-12">
                                {% if facts|length > 0 %}
                                    <h2><i class="fa-solid fa-check"></i> {{ facts|length }} Faits passés à confirmer
                                    </h2>
                                {% endif %}
                                <a href="{{ path('app_create_fact') }}"><i class="fa-solid fa-plus-circle fa-2x"></i>
                                    <h3>Créer un nouveau fait</h3>
                                </a>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <table class="table table-striped table-middle-aligned">
                                    <thead>
                                    <tr>
                                        <th scope="col">Titre</th>
                                        <th scope="col"><i class="fa fa-calendar" aria-hidden="true"></i> Date</th>
                                        <th scope="col"><i class="fa-solid fa-circle-info"></i> Description</th>
                                        <th scope="col"><i class="fa fa-cogs" aria-hidden="true"></i>
                                            Actions
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for fact in facts %}
                                        <tr>
                                            <td>{{ fact.name }}</td>
                                            <td>{{ fact.dateFact | date('d/m/Y') }}</td>
                                            <td>{{ fact.description }}</td>
                                            <td class="text-right">
                                                <div class="item-actions">
                                                    <a href="{{ path('app_edit_fact', {id: fact.id}) }}"
                                                       class="btn btn-sm btn-default">
                                                        <i class="fa fa-edit" aria-hidden="true"></i> Modifier le fait
                                                    </a>
                                                </div>
                                            </td>
                                        </tr>
                                    {% else %}
                                        <tr>
                                            <td colspan="4" align="center">Aucun Fait trouvé</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                                <div class="d-flex justify-content-center">
                                    {{ knp_pagination_render(facts, 'base/pagination.html.twig') }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6">
                    <div class="container">
                        <div class="row">
                            <div class="col-12">
                                {% if projects|length > 0 %}
                                    <h2><i class="fa-solid fa-bars"></i> Mes projets</h2>
                                    <a href="{{ path('app_create_project') }}"><i
                                                class="fa-solid fa-plus-circle fa-2x"></i>
                                        <h3>Créer un nouveau projet</h3></a>
                                {% else %}
                                    <h2><i class="fa-solid fa-bars"></i> Aucun projet trouvé</h2>
                                {% endif %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <table class="table table-striped table-middle-aligned">
                                    <thead>
                                    <tr>
                                        <th scope="col">Titre</th>
                                        <th scope="col"><i class="fa fa-calendar" aria-hidden="true"></i> Commencé le
                                        </th>
                                        <th scope="col"><i class="fa fa-calendar" aria-hidden="true"></i> Fini le</th>
                                        <th scope="col"><i class="fa fa-cogs" aria-hidden="true"></i>
                                            Actions
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for project in projects %}
                                        <tr>
                                            <td>{{ project.title }}</td>
                                            <td>{{ project.startDate | date('d/m/Y') }}</td>
                                            <td>{{ project.endedAt | date('d/m/Y') }}</td>
                                            <td class="text-right">
                                                <div class="item-actions">
                                                    <a href="{{ path('app_show_project', {id: project.id}) }}"
                                                       class="btn btn-sm btn-default">
                                                        <i class="fa fa-eye" aria-hidden="true"></i> Voir le projet
                                                    </a>
                                                    <a href="{{ path('app_edit_project', {id: project.id}) }}"
                                                       class="btn btn-sm btn-default">
                                                        <i class="fa fa-edit" aria-hidden="true"></i> Modifier le projet
                                                    </a>
                                                </div>
                                            </td>
                                        </tr>
                                    {% else %}
                                        <tr>
                                            <td colspan="4" align="center">Aucun Projet trouvé</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <a href="{{ path('app_projects') }}" class="btn btn-sm btn-default">
                                    <i class="fa fa-eye" aria-hidden="true"></i> Afficher tous mes projets
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6">
                    <h2><i class="fa-regular fa-pen-to-square"></i> Derniers projets mis à jour</h2>
                    <ul>
                        <li>
                            <p> Test</p>
                        </li>
                        <li>
                            <p> Test</p>
                        </li>
                    </ul>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6">
                    <h2><i class="fa-solid fa-clock"></i> Projets prévus</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <h2><i class="fa-solid fa-folder"></i> Nombre de projets par statut</h2>
                    {% for status in status %}
                        <ul>
                            <li>
                                <p>{{ status.name }} : {{ status|length }} projet(s)</p>
                            </li>
                        </ul>
                    {% else %}
                        <tr>
                            <td colspan="4" align="center">Aucun status trouvé</td>
                        </tr>
                    {% endfor %}

                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <h2><i class="fa-solid fa-calendar"></i> Derniers jalons majeurs</h2>
                    <a href="{{ path('app_create_milestone') }}"><i class="fa-solid fa-plus-circle fa-2x"></i>
                        <h3>Créer un nouveau jalon</h3></a>
                    <table class="table table-striped table-middle-aligned">
                        <thead>
                        <tr>
                            <th scope="col"> Nom</th>
                            <th scope="col"> Valeur</th>
                            <th scope="col">Mandataire</th>
                            <th scope="col"><i class="fa fa-cogs" aria-hidden="true"></i>
                                Actions
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for milestone in milestones %}
                            <tr>
                                <td><a href="#">{{ milestone.name }}</a></td>
                                <td>{{ milestone.value }}</td>
                                <td>{{ milestone.mandatory }}</td>
                                <td class="text-right">
                                    <div class="item-actions">
                                        <a href="{{ path('app_edit_milestone', {id: milestone.id}) }}"
                                           class="btn btn-sm btn-default">
                                            <i class="fa fa-edit" aria-hidden="true"></i> Modifier le jalon
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="4">Aucun Projet trouvé</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <div class="d-flex justify-content-center">
                        {{ knp_pagination_render(milestones, 'base/pagination.html.twig') }}
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <div class="row d-flex align-items-center justify-content-center text-center">
            <div class="col-md-10 col-12">
                <h1>Bienvenue</h1>
                <h2>Veuillez vous connecter ou vous enregistrer</h2>
            </div>
        </div>
    {% endif %}

    {% include 'base/footer.html.twig' %}
{% endblock %}

templates/project/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Nouveau projet
{% endblock %}

{% block body %}

    {% include 'base/nav.html.twig' %}
    <h1 class="text-center py-5">Modifier un projet</h1>

    {{ include("project/_form.html.twig", { button_label: "Enregistrer" }) }}

    <div class="d-flex justify-content-evenly align-items-center mb-3">
        <a href="{{ path('app_homepage') }}">
            <i class="fa-solid fa-arrow-left-long fa-2x"></i>
        </a>

    </div>
    {% include 'base/footer.html.twig' %}

{% endblock %}

templates/project/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Projet {{ project.id }}{% endblock %}

{% block body %}
    {% include 'base/nav.html.twig' %}

    <h1>Projet n°{{ project.id }}</h1>
    <h2>{{ project.title }}</h2>
    <p>{{ project.description }}</p>
    <small>crée le {{ project.startDate | date('d/m/Y') }}</small> <br>
    <small>terminé le {{ project.endedAt | date('d/m/Y') }}</small>

    <h2> Les risques</h2>
    <a href="{{ path('app_create_risk') }}"><i class="fa-solid fa-plus-circle fa-2x"></i><h3>Créer un nouveau risque</h3> </a>

    <table class="table table-striped table-middle-aligned">
        <thead>
        <tr>
            <th scope="col">Titre</th>
            <th scope="col"><i class="fa fa-calendar" aria-hidden="true"></i> Commencé le</th>
            <th scope="col"><i class="fa fa-calendar" aria-hidden="true"></i> Fini le</th>
            <th scope="col" class="text-center"><i class="fa fa-cogs" aria-hidden="true"></i> Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for risk in risks %}
            <tr>
                <td>{{ risk.name }}</td>
                <td>{{ risk.IdentificationDate | date('d/m/Y') }}</td>
                <td>{{ risk.ResolutionDate | date('d/m/Y') }}</td>
                <td class="text-right">
                    <div class="item-actions">
                        <a href="{{ path('app_edit_risk', {id: risk.id}) }}"
                           class="btn btn-sm btn-default">
                            <i class="fa fa-edit" aria-hidden="true"></i> Modifier le risque
                        </a>
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4" align="center">Aucun risque trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <h2> Les budgets du projet</h2>

    <table class="table table-striped table-middle-aligned">
        <thead>
        <tr>
            <th scope="col">Titre</th>
            <th scope="col"><i class="fa fa-calendar" aria-hidden="true"></i> Commencé le</th>
            <th scope="col"><i class="fa fa-calendar" aria-hidden="true"></i> Fini le</th>
            <th scope="col" class="text-center"><i class="fa fa-cogs" aria-hidden="true"></i> Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for budget in budgets %}
            <tr>
                <td>{{ budget.initialValue }}</td>
                <td>{{ budget.consumedValue }}</td>
                <td>{{ budget.remainingBudget }}</td>
                <td class="text-right">
                    <div class="item-actions">
                        <a href="{{ path('app_edit_budget', {id: budget.id})  }}" class="btn btn-sm btn-default">
                            <i class="fa fa-edit" aria-hidden="true"></i> Modifier le budget
                        </a>
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">Aucun budget trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <h2> Les jalons</h2>
    <a href="{{ path('app_create_milestone') }}"><i class="fa-solid fa-plus-circle fa-2x"></i><h3>Créer un nouveau jalon</h3> </a>

    <table class="table table-striped table-middle-aligned">
        <thead>
        <tr>
            <th scope="col">Titre</th>
            <th scope="col"><i class="fa fa-calendar" aria-hidden="true"></i> Commencé le</th>
            <th scope="col"><i class="fa fa-calendar" aria-hidden="true"></i> Fini le</th>
            <th scope="col" class="text-center"><i class="fa fa-cogs" aria-hidden="true"></i> Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for milestone in milestones %}
            <tr>
                <td>{{ milestone.name }}</td>
                <td>{{ milestone.value }}</td>
                <td>{{ milestone.mandatory }}</td>
                <td class="text-right">
                    <div class="item-actions">
                        <a href="{{ path('app_edit_milestone', {id: milestone.id})  }}" class="btn btn-sm btn-default">
                            <i class="fa fa-eye" aria-hidden="true"></i> Editer le jalon
                        </a>
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">Aucun Jalon trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}